import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Gloock,
  Inter,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = Gloock({
  variable: "--font-mono",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prodigy Photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable} scroll-smooth h-full antialiased  `}
    >
      <body className="min-h-full font-sans text-gray-700">{children}</body>
    </html>
  );
}
